project:
  type: website
  output-dir: docs
website:
  title: "Heeju Lim"
  navbar:
    left:
      - text: About
        href: "#about"

      - text: Publications
        href: "#publications"

      - text: Presentations
        href: "#presentations"
      
      - text: Teaching
        href: "#teaching"
        
      - text: CV
        href: "#cv"
 
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    page-layout: full
    fontsize: 1em


editor: visual

