project:
  type: website
  output-dir: docs
website:
  title: "Heeju Lim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - project.qmd
      - posts.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    fontsize: 1.1em


editor: visual

